# Generated by Django 2.0.6 on 2018-06-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibu', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('abv', models.FloatField(default=None)),
                ('style', models.CharField(default=None, max_length=100)),
                ('brewery_location', models.CharField(default=None, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aroma', models.IntegerField()),
                ('appearance', models.IntegerField()),
                ('taste', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
