# Generated by Django 2.0.6 on 2018-06-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerapp', '0003_review_beer'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
