# Generated by Django 2.0.6 on 2018-06-28 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerapp', '0006_auto_20180628_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='abv',
            field=models.FloatField(default=4.5, validators=[django.core.validators.MaxValueValidator(4.2), django.core.validators.MinValueValidator(4.5)]),
        ),
        migrations.AlterField(
            model_name='beer',
            name='calories',
            field=models.IntegerField(default=64, validators=[django.core.validators.MaxValueValidator(198), django.core.validators.MinValueValidator(64)]),
        ),
        migrations.AlterField(
            model_name='beer',
            name='ibu',
            field=models.IntegerField(default=30, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(30)]),
        ),
    ]
