# Generated by Django 2.0.6 on 2018-06-28 02:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerapp', '0007_auto_20180628_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='abv',
            field=models.FloatField(default=4.5, validators=[django.core.validators.MaxValueValidator(6.2), django.core.validators.MinValueValidator(4.5)]),
        ),
    ]
